variables:
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/poetry"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .cache/poetry
    - .venv/

before_script:
  - python -V  # Print out python version for debugging
  - poetry install

test:
  script:
    - pwd
    - poetry run bioblue --version
