# variables:
#   POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/poetry"
#   PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
#   TMPDIR: "$CI_PROJECT_DIR/.tmp"

# cache:
#   paths:
#     - .cache/pip
#     - .cache/poetry

before_script:
  - poetry install
  - which git
  - git --version
  - module list

update_git:
  script:
    - pwd
    - ls -lah
    - which python
    - poetry run which python
    - poetry env list
# test:
#   script:
#     - poetry run bioblue --version
#     - poetry run pytest
