# variables:
#   POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/poetry"
#   PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
#   TMPDIR: "$CI_PROJECT_DIR/.tmp"

# cache:
#   paths:
#     - .cache/pip
#     - .cache/poetry

before_script:
  - poetry install
  # - ssh -o ExitOnForwardFailure=yes -f -N -L 9000:localhost:9000 betelgeuse
  # - ssh -o ExitOnForwardFailure=yes -f -N -L 5000:localhost:5000 betelgeuse

print_help:
  script:
    - poetry run bioblue --help
    - echo "done"

test:
  script:
    - poetry run bioblue exp=test
    - echo "done"
