# variables:
#   POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/poetry"
#   PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
#   TMPDIR: "$CI_PROJECT_DIR/.tmp"

# cache:
#   paths:
#     - .cache/pip
#     - .cache/poetry

# before_script:
#   - cd $CECIHOME

update_git:
  script:
    - pwd
    - ls
# test:
#   script:
#     - poetry run bioblue --version
#     - poetry run pytest
