defaults:
  - _self_
  - trainer: default
  - model: conf_unet
  - module: semantic_blurring
  - dataset: synthetic
  - logger: "mlflow"
  - server: "${host:}"
  - exp: test
  # - override hydra/launcher: gpu

seed: 0
hydra:
  job:
    env_set:
      AWS_ACCESS_KEY_ID: vjoosdtb
      AWS_SECRET_ACCESS_KEY: qsdfghjk
      MLFLOW_S3_ENDPOINT_URL: "http://betelgeuse.elen.ucl.ac.be:9000"
      MLFLOW_TRACKING_URI: "http://betelgeuse.elen.ucl.ac.be:5000"
      MLFLOW_S3_IGNORE_TLS: "true"
