_target_: deep_blueprint.module.BaseClassifier
# input_format: ['image']
classifier: "${model}"
loss:
  _target_: torch.nn.CrossEntropyLoss
# scheduler:
#   _target_: torch.optim.lr_scheduler.MultiStepLR
#   milestones: [10, 30, 50]
#   gamma: 0.1
lr: 1.e-4
# class_weights: [1,1,1]