data_dir: "${oc.env:HOME}/projects/bio-blueprints/data"
dataset_name: Task203_BrainVessels
batch_size: 4
num_workers: 12
strategies:
    kfold:
      _target_: bioblue.dataset.KFoldStrategy
      fold: 0
      folds: 2