# @package _group_
_target_: bioblue.dataset.ThresholdableDataModule
data_dir: "${env:HOME}/projects/bio-blueprints/data"
directory: "kidneys"
batch_size: 4
num_workers: 12
threshold_mean: 0.999
threshold_std: 0.001
