defaults:
  - base_dataset

dataset_name: "PA_fibers_crop3d_128"
batch_size: 1
fold: "???"
strategies:
  preprocess:
    _target_: bioblue.dataset.DICOMPrepStrategy
    base_dir: "${oc.env:HOME}/projects/bb-data/PA_Fibers"
    directories:
      s1_4: ["s1_4", null]
  crop:
    _target_: bioblue.dataset.FiberCrop3dStrategy
    crop_size: 128
    grid_size: 128
  segmentation:
    _target_: bioblue.dataset.FiberSegStrategy
  kfold:
    _target_: bioblue.dataset.KFoldStrategy
    fold: ${dataset.fold}
    folds: 6
train_dataset:
  _target_: bioblue.dataset.SummaryNumpyDataset
  partition: "train"
  dtypes: ["segmentation", "image"]
  transforms:
    _target_: monai.transforms.Compose
    transforms:
      - _target_: monai.transforms.CopyItemsd
        keys: ["segmentation", "image"]
        times: 1
        names: ["segm_init", "img_init"]
      - _target_: monai.transforms.AddChanneld
        keys: ["image", "segmentation"]
      - _target_: bioblue.dataset.transform.RandomSegmThreshold
        keys: ["segmentation"]
        scale: ${threshold.scale}
        thresh_neg: ${threshold.neg}
        thresh_pos: ${threshold.pos}
      - _target_: monai.transforms.RandRotated
        keys: ["image", "segmentation"]
        range_x: 3.14
        range_y: 3.14
        range_z: 3.14
        prob: 1.0
        mode: ["bilinear", "nearest"]
        padding_mode: "zeros"
      - _target_: monai.transforms.SqueezeDimd
        keys: ["image", "segmentation"]
      - _target_: bioblue.dataset.transform.ShowHisto
        keys: ["segm_init", "segmentation", "img_init", "image"]
      # - _target_: monai.transforms.SelectItemsd
      #   keys: ["image", "segmentation"]
    # - _target_: bioblue.dataset.transform.RandomBackgroundAdd
    #   p_background: 0.05
    # - _target_: bioblue.dataset.transform.DropSegmentation
    #   p_dropout: 0.5
    # - _target_: albumentations.Rotate
    #   limit: 90
    #   border_mode: 0
    #   value: 0
    #   mask_value: 0
    # - _target_: albumentations.CropAndPad
    #   percent: [-0.2, 0]
    #   keep_size: true
    #   interpolation: 0
val_dataset:
  _target_: bioblue.dataset.SummaryNumpyDataset
  partition: "train"
  dtypes: ["segmentation", "image"]