# @package _group_
_target_: bioblue.dataset.BioblueDataModule
data_dir: "${env:HOME}/projects/bio-blueprints/data" # set in server config
dataset_name: "PA_fibers_crop"
batch_size: 32
num_workers: 12 # set in server config
fold: "???"
strategies:
  preprocess:
    _target_: bioblue.dataset.DICOMPrepStrategy
    base_dir: "${env:HOME}/projects/bb-data/PA_Fibers"
    directories:
      s1_4: ["s1_4", null]
  kfold:
    _target_: bioblue.dataset.KFoldStrategy
    fold: ${dataset.fold}
    folds: 6
  # crop:
  #   _target_: bioblue.dataset.FiberCropStrategy
  #   crop_size: 256
  #   grid_size: 200
  # segmentation:
  #   _target_: bioblue.dataset.FiberSegStrategy
train_dataset:
  _target_: bioblue.dataset.MultipleNumpyDataset
  partition: "train"
  dtypes: ["segmentation", "image"]
  transforms:
    - _target_: albumentations.Rotate
      limit: 90
      border_mode: 0
      value: 0
      mask_value: 0
    - _target_: albumentations.CropAndPad
      percent: [-0.2, 0]
      keep_size: true
      interpolation: 0
val_dataset:
  _target_: bioblue.dataset.MultipleNumpyDataset
  partition: "train"
  dtypes: ["segmentation", "image"]
test_dataset: ${dataset.val_dataset}