defaults:
  - pa_synth

dataset_name: "PA_synth"
batch_size: 1
strategies:
  preprocess:
    _target_: bioblue.dataset.SummaryStrategy
train_dataset:
  _target_: bioblue.dataset.SummaryNumpyDataset
  partition: "train"
  dtypes: ["segmentation", "image"]
  transforms:
    _target_: monai.transforms.Compose
    transforms:
      - _target_: monai.transforms.CopyItemsd
        keys: ["segmentation", "image"]
        times: 1
        names: ["segm_init", "img_init"]
      - _target_: monai.transforms.AddChanneld
        keys: ["image", "segmentation"]
      - _target_: monai.transforms.RandGaussianSmoothd
        keys: ["image"]
        sigma_x: [0.25, 1.5]
        sigma_y: [0.25, 1.5]
        sigma_z: [0.25, 1.5]
        prob: 0.5
      - _target_: monai.transforms.RandHistogramShiftd
        keys: ["image"]
        num_control_points: [3, 10]
        prob: 1.0
      - _target_: monai.transforms.RandAdjustContrastd
        keys: ["image"]
        gamma: [0.5, 3.5]
        prob: 1.0
      - _target_: monai.transforms.RandRotated
        keys: ["image", "segmentation"]
        range_x: 0
        range_y: 0
        range_z: 0
        prob: 1.0
        mode: ["bilinear", "nearest"]
        padding_mode: "zeros"
      - _target_: monai.transforms.SqueezeDimd
        keys: ["image", "segmentation"]
      - _target_: bioblue.dataset.transform.ShowHisto
        keys: ["img_init", "image"]
      # - _target_: monai.transforms.SelectItemsd
      #   keys: ["image", "segmentation"]
    # - _target_: bioblue.dataset.transform.RandomBackgroundAdd
    #   p_background: 0.05
    # - _target_: bioblue.dataset.transform.DropSegmentation
    #   p_dropout: 0.5
    # - _target_: albumentations.Rotate
    #   limit: 90
    #   border_mode: 0
    #   value: 0
    #   mask_value: 0
    # - _target_: albumentations.CropAndPad
    #   percent: [-0.2, 0]
    #   keep_size: true
    #   interpolation: 0
val_dataset:
  _target_: bioblue.dataset.SummaryNumpyDataset
  partition: "val"
  dtypes: ["segmentation", "image"]
  transforms:
    _target_: monai.transforms.Compose
    transforms:
      - _target_: monai.transforms.AddChanneld
        keys: ["image", "segmentation"]
      - _target_: bioblue.dataset.transform.MapLabels
        mapping: {2: 0} # Remove valleys from dataset
      - _target_: monai.transforms.SqueezeDimd
        keys: ["image", "segmentation"]
      - _target_: monai.transforms.SelectItemsd
        keys: ["image", "segmentation"]