# @package _group_
_target_: bioblue.dataset.SyntheticDataModule
data_dir: "${env:HOME}/projects/bio-blueprints/data"
directory: "synthetic"
train_size: 50
val_size: 50
test_size: 50
shape: [512, 512]
batch_size: 4
image_creator:
  _target_: bioblue.dataset.create_lines
  blur_sigma: 15
  uniform_background: False
  foreground_params:
    points_range: [5,20]
    links_range: [2,4]
    weight_range: [1,5]
    intensity_range: [100, 255]
  background_params:
    min_shapes: 10
    max_shapes: 100
    min_size: 50
    max_size: 500
    intensity_range: [0, 128]
    allow_overlap: True