# @package _group_
_target_: bioblue.dataset.SyntheticDataModule
data_dir: "${env:HOME}/projects/bio-blueprints/data"
directory: "synthetic"
train_size: 50
val_size: 50
test_size: 50
shape: [512, 512]
batch_size: 4
