# @package _global_
trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 30
  gpus: ${gpus}
  auto_scale_batch_size: false
  log_every_n_steps: 2

logger:
  - _target_: pytorch_lightning.loggers.WandbLogger
    # name: 'test'
    project: 'Deepsun'
    save_dir: "."



module:
  optimizer: torch.optim.AdamW
  # ######## WORKS
  loss:
    _target_: bioblue.loss.CombineLosses
    sublossA: 
      _target_: torch.nn.CrossEntropyLoss
    sublossB: 
      _target_: bioblue.loss.LogCosHDiceLoss
      softmax: true
      to_onehot_target: true
      include_background: true
    ce_ratio: 0.5
    include_background: true
  
  class_weights: [1,20]
  
  scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 250
    gamma: 0.9
    last_epoch: -1

model:
  input_format: ["image"]
  output_format: ["segmentation"]
  # classes: [ "penumbra", "umbra"]
  classes: [ "sunspot"]
  _target_: bioblue.model.ConfUnet
  model_cfg:
    _target_: bioblue.model.ModelConfig
  block: double
  architecture:
    first: 32
    enc:
      width: [32, 64, 128, 256, 512, 512, 512]
      repeat: [1,1,1,1,1,1,1]
    dec:
      width: [512, 512, 256, 128, 64, 32]
      repeat: [1, 1, 1, 1, 1, 1]



use_dtypes: "???"

dataset:
  _target_: bioblue.dataset.BioblueDataModule
  data_dir: "/globalscratch/users/n/s/nsayez/deepsun_bioblue/"
  dataset_name: "All"
  batch_size: 16
  num_workers: 12
  
  train_dataset:
    _target_: bioblue.dataset.DeepsunSegmentationDataset
    partition: "train"
    dtypes: ${use_dtypes}

    transforms:
      - _target_: bioblue.transforms.DeepsunRandomFlip
      - _target_: bioblue.transforms.DeepsunRandomRotate
      - _target_: bioblue.transforms.DeepsunCropNonEmptyMaskIfExists
        height: 512
        width: 512
      - _target_: bioblue.transforms.DeepsunRandomMaskSelector
      # - _target_: bioblue.transforms.DeepsunMaskMerger
      #   p_add: 0.5
        

  val_dataset:
    _target_: bioblue.dataset.DeepsunSegmentationDataset
    partition: "test"
    dtypes: ${use_dtypes}
    transforms:
      - _target_: bioblue.transforms.DeepsunRandomFlip
      - _target_: bioblue.transforms.DeepsunRandomRotate
      - _target_: bioblue.transforms.DeepsunCropNonEmptyMaskIfExists
        height: 512
        width: 512
      - _target_: bioblue.transforms.DeepsunMaskMerger
        p_add: 0.5

  test_dataset:     
    _target_: bioblue.dataset.DeepsunSegmentationTestDataset
    partition: "test_GT"
    dtypes: ['image', 'GroundTruth']
    patch_side: 512
    transforms:
      - _target_: bioblue.transforms.DeepsunRandomFlip
      - _target_: bioblue.transforms.DeepsunRandomRotate
      - _target_: bioblue.transforms.DeepsunCropNonEmptyMaskIfExists
        height: 512
        width: 512

callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: "./models"
    save_last: true
    monitor: val_meaniou
    mode: max
    filename: "{epoch}-{val_meaniou:.2f}"
  wandb:
    _target_: bioblue.callback.WandBCallback
    log_models: false
  LR_monitor:
    _target_: "pytorch_lightning.callbacks.LearningRateMonitor"
  Save_prediction:
    _target_: 'bioblue.callback.SavePredictionMaskCallback2'
    output_dir: 'predictions'
    max_batch_size: ${dataset.batch_size}
