# @package _global_
exp: MIP
dataset:
  _target_: bioblue.dataset.BioblueDataModule
  train_dataset:
    _target_: bioblue.dataset.MultipleNumpyDataset
    root_dir: "${dataset.data_dir}/train"
    dtypes: ["image", "mip-image", "segmentation"]
  val_dataset: ${dataset.train_dataset}
  test_dataset: ${dataset.train_dataset}
  strategies:
    mip:
      _target_: bioblue.dataset.MIPStrategy
      source_dtype: image
      dtype_prefix: mip
      size: 5
model:
  input_format: ["image", "mip-image"]
callbacks:
  - _target_: bioblue.callback.MLFlowCallback
    log_models: true
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: "./models"
    save_last: true
    monitor: val_meaniou
    mode: max
    filename: "{epoch}-{val_meaniou:.2f}"
  - _target_: "pytorch_lightning.callbacks.LearningRateMonitor"