# @package _global_
trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 30
  gpus: ${gpus}
  auto_scale_batch_size: false
  log_every_n_steps: 2

logger:
  - _target_: pytorch_lightning.loggers.WandbLogger
    # name: 'test'
    project: 'Deepsun'
    save_dir: "."



module:
  optimizer: 'torch.optim.SGD'
  # ######## WORKS
  lr: 1.e-5
  loss:
    _target_: torch.nn.CrossEntropyLoss # <--- WORKS
    # _target_: torch.nn.BCELoss 
    # ignore_index: 0
  class_weights: [1,20]

model:
  input_format: ["image"]
  output_format: ["segmentation"]
  # classes: [ "penumbra", "umbra"]
  classes: [ "sunspot"]
  _target_: bioblue.model.ConfUnet
  model_cfg:
    _target_: bioblue.model.ModelConfig
  block: double
  architecture:
    first: 32
    enc:
      width: [32, 64, 128, 256, 512, 512, 512]
      repeat: [1,1,1,1,1,1,1]
    dec:
      width: [512, 512, 256, 128, 64, 32]
      repeat: [1, 1, 1, 1, 1, 1]



use_dtypes: "???"

dataset:
  _target_: bioblue.dataset.BioblueDataModule
  data_dir: "/DATA/datasets/niels/Deepsun/bioblue/"
  dataset_name: "2013"
  batch_size: 6
  num_workers: 12
  
  train_dataset:
    _target_: bioblue.dataset.DeepsunSegmentationDataset
    partition: "train"
    dtypes: ${use_dtypes}

    transforms:
      - _target_: bioblue.transforms.DeepsunRandomFlip
      - _target_: bioblue.transforms.DeepsunRandomRotate
      - _target_: bioblue.transforms.DeepsunCropNonEmptyMaskIfExists
        height: 512
        width: 512
      - _target_: bioblue.transforms.DeepsunMaskMerger
        p_add: 0.5
        

  val_dataset:
    _target_: bioblue.dataset.DeepsunSegmentationDataset
    partition: "test"
    dtypes: ${use_dtypes}
    transforms:
      - _target_: bioblue.transforms.DeepsunRandomFlip
      - _target_: bioblue.transforms.DeepsunRandomRotate
      - _target_: bioblue.transforms.DeepsunCropNonEmptyMaskIfExists
        height: 512
        width: 512
      - _target_: bioblue.transforms.DeepsunMaskMerger
        p_add: 0.5

  test_dataset:     
    _target_: bioblue.dataset.DeepsunSegmentationDataset
    partition: "test_GT"
    dtypes: ['image', 'GroundTruth']
    transforms:
      - _target_: bioblue.transforms.DeepsunRandomFlip
      - _target_: bioblue.transforms.DeepsunRandomRotate
      - _target_: bioblue.transforms.DeepsunCropNonEmptyMaskIfExists
        height: 512
        width: 512

callbacks:
  wandb:
    _target_: bioblue.callback.WandBCallback
    log_models: false
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: "./models"
    save_last: true
    monitor: val_meaniou
    mode: max
    filename: "{epoch}-{val_meaniou:.2f}"
  LR_monitor:
    _target_: "pytorch_lightning.callbacks.LearningRateMonitor"
  Save_prediction:
    _target_: 'bioblue.callback.SavePredictionMaskCallback'
    output_dir: 'predictions'
    max_batch_size: ${dataset.batch_size}
