# @package _global_
defaults:
  - override /dataset: pa_synth
  - override /module: base_segmentation
  - override /model: conf_unet
  - override /logger: none

exp: Fibers3dSynth
dataset:
  num_workers: 12
threshold:
  scale: 5
  neg: 0
  pos: 255
model:
  input_format: ["image"]
  output_format: ["segmentation"]
  classes: ["fiber"]
  model_cfg:
    _target_: bioblue.model.Model3dConfig
module:
  loss:
    _target_: torch.nn.CrossEntropyLoss
  class_weights: [1,2]
callbacks:
  # mlflow:
  #   _target_: bioblue.callback.MLFlowCallback
  #   log_models: true
  # model_checkpoint:
  #   _target_: pytorch_lightning.callbacks.ModelCheckpoint
  #   dirpath: "./models"
  #   save_last: true
  #   monitor: val_meaniou
  #   mode: max
  #   filename: "{epoch}-{val_meaniou:.2f}"
  lr_monitor:
    _target_: "pytorch_lightning.callbacks.LearningRateMonitor"
  save_volumes:
    _target_: bioblue.callback.SaveVolumeCallback
    train: true
    val: true
    period: 2