# @package _global_
exp: Kidneys
module:
  _target_: bioblue.module.ThresholdSegment
  segmenter: ${model}
callbacks:
  - _target_: bioblue.callback.MLFlowCallback
    log_models: true
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: "./models"
    save_last: true
    monitor: val_meaniou
    mode: max
    filename: "{epoch}-{val_meaniou:.2f}"
  - _target_: "pytorch_lightning.callbacks.LearningRateMonitor"