# @package _global_
exp: Threshold
model:
  input_format: ["image"]
  output_format: ["segmentation"]
module:
  class_weights: [1,10]
callbacks:
  mlflow:
    _target_: bioblue.callback.MLFlowCallback
    log_models: true
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: "./models"
    save_last: true
    monitor: val_meaniou
    mode: max
    filename: "{epoch}-{val_meaniou:.2f}"
  lr_monitor:
    _target_: "pytorch_lightning.callbacks.LearningRateMonitor"
  save_volumes:
    _target_: bioblue.callback.SaveVolumeCallback
    train: true
    val: true